# Generated by Django 3.2.5 on 2021-07-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_api', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_api.form')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.CharField(default='text', max_length=255)),
                ('number_field', models.IntegerField(default=0)),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datetime_field', models.DateTimeField(auto_now_add=True)),
                ('date_field', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_api.customer')),
                ('option_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_api.option')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_api.part')),
            ],
        ),
    ]
